version: '3.8'

services:
  kafka2:
    image: apache/kafka:4.0.0
    container_name: kafka2
    ports:
      - "9094:9094"  # наружный порт может отличаться
#      - "9094:9092"  # наружный порт может отличаться
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://<SERVER2_PUBLIC_IP>:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@<SERVER1_PUBLIC_IP>:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CLUSTER_ID: MyKafkaCluster123
    volumes:
      - kafka2-data:/var/lib/kafka
    command:
      - bash
      - -c
      - |
        kafka-server-start.sh /etc/kafka/kafka.properties

volumes:
  kafka2-data:
